language: php

dist: bionic

php:
  - 8.2

services:
  - mysql
  - redis

before_script:
    - mysql -e "CREATE DATABASE example_app"
  - composer self-update
  - composer install --no-interaction --prefer-source
  - npm install
  - npm run build
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit
